name: python-api-app-3-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag for dockerhub version
        shell: bash
        run: |
          echo "IMAGE_VERSION=$(date +'%y%m%d-%H%M')" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnyunez/python-api-app-3:${{ env.IMAGE_VERSION }}
    outputs:
      image_version: ${{ env.IMAGE_VERSION }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Install pip and yq & Update charts/values/image.tag tag with new dockerhub image
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y python3-venv python3-pip
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip install yq
          echo ${{ needs.ci.outputs.image_version }}
          yq -Yi '.image.tag = "${{ needs.ci.outputs.image_version }}"' ./charts/values-dev.yaml
      -
        name: Commit changes to charts/values/image.tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "github-actions.cd: update image tag to ${{ needs.ci.outputs.image_version }}"
          branch: master
          file_pattern: "charts/values-dev.yaml"
      -
        name: Install Argocd + Argocd login + repo add +  app create + app sync
        shell: bash
        run: |
          sudo curl -sSLk -o /usr/local/bin/argocd https://argocd-server.argocd/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd 

          repo="https://github.com/YuneZoft/python-api-app-3.git"
          argocd login argocd-server.argocd \
            --insecure \
            --username ${{ vars.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}

          argocd repo list | grep -q $repo \
            || argocd repo add $repo \
                --project default \
                --name python-api-app-3

          argocd app get python-api-app-3 \
          || argocd app create python-api-app-3 \
            --repo $repo \
            --path charts \
            --revision master \
            --dest-namespace python-api-app-3-dev \
            --values values-dev.yaml \
            --dest-server https://kubernetes.default.svc \
            --sync-policy manual \
            --sync-option CreateNamespace=true

          argocd app sync python-api-app-3

          argocd app wait python-api-app-3 --health --timeout 300


